version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 356530442800.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t devops:latest .
      - echo Running tests...
      # - pytest --maxfail=1 --disable-warnings --tb=short
      - echo tagging the Docker image...
      - docker tag devops:latest 356530442800.dkr.ecr.us-east-1.amazonaws.com/devops:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 356530442800.dkr.ecr.us-east-1.amazonaws.com/devops:latest
      - echo Writing Image Definitions file...
      - printf '[{"name":"Container-app-python","imageUri":"356530442800.dkr.ecr.us-east-1.amazonaws.com/devops:latest"}]' > imagedefinitions.json
      - printf '{"ImageURI":"356530442800.dkr.ecr.us-east-1.amazonaws.com/devops:latest"}' > imageDetail.json
      - cat imagedefinitions.json
artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
    - imageDetail.json
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json
